### ISSUE TITLE
Newcomer problems

### ISSUE THREAD

**Issue by PMatthaei** [StatsHelix/demoinfo#107]
Hi guys,

I am realtively new to C# and demofile parsing. I wanted to subscribe to playerHurt event but i get told that DemoParser does not contain the defintion "PlayerHurt" although it is implemented and defined. 
Can somebody tell me why this is happening? It also tells me that PlayerHurtEventArgs namespace/type could not be found. I used this https://github.com/EHVAG/demostatistics-generator as a template (the Generator Classes)

Thanks in advance.
`

**Comment by moritzuehling** [comment]
Hey, can you send a gist (http://gist.github.com) of the method where the 
error occures and the exact error message?

**Comment by PMatthaei** [comment]
Here is the gist(hope i did it right^^) https://gist.github.com/PMatthaei/d974868bf2749d088fa0af1713139637
 Error Messages are:

Error	CS1061	'DemoParser' does not contain a definition for 'PlayerHurt' and no extension method 'PlayerHurt' accepting a first argument of type 'DemoParser' could be found (are you missing a using directive or an assembly reference?)

Error	CS0246	The type or namespace name 'PlayerHurtEventArgs' could not be found (are you missing a using directive or an assembly reference?)

**Comment by PMatthaei** [comment]
I found out that if i copy the DemoInfo.dll from release of DemoInfo to StatisticsGenerator i wont get this error anymore but instead problems with the assembly. Any clue?

**Comment by PMatthaei** [comment]
Please can someone help me. Google does not bring any help and i cant find the problem in code or assembly files. The marked reference in the picture does not contain all events  and therefore i cant use them. why ? :(

![fail](https://cloud.githubusercontent.com/assets/8292508/16954376/f3d6faa2-4dd0-11e6-90ba-a7488c396108.png)

**Comment by moritzuehling** [comment]
Hey, sorry - I've been busy the last few days. 

These are mainly C#-Questions. The right way to setup a new project is as following. 

## 1) Create the new Project in Visual Studio. 

## 2) Open the NuGet Package manager

![image](https://cloud.githubusercontent.com/assets/7847742/17018432/0769eed6-4f38-11e6-806d-e46564b6c934.png)

## 3) Add our Library

![image](https://cloud.githubusercontent.com/assets/7847742/17018460/227c312a-4f38-11e6-94a3-5fbf0c32507e.png)

## 4) Enjoy working with the Library! 

The gist you posted compiles without problems now.

**Comment by moritzuehling** [comment]
Since I assume it works now I'm gonna close it, just reply and re-open it if you need more help :)

**Comment by PMatthaei** [comment]
Thanks! Everything works :) i might have never considered nuget to solve this.
