### ISSUE TITLE
Missing events(Jumping, Steps, Flashduration)(?)

### ISSUE THREAD

**Issue by PMatthaei** [StatsHelix/demoinfo#108]
Hi guys,

i noticed that there is no bool or event for jumping and steps(hearable movement).
Also i found code for flashduration(when downloading the zip on github) but no flashduration in the nuget version. Are these coming soon?

Regards

**Comment by moritzuehling** [comment]
> i noticed that there is no bool or event for jumping and steps(hearable movement).

You can add the events [here](https://github.com/StatsHelix/demoinfo/blob/ba77851accf72bb8c0bdce7e02fedb54d13f7acb/DemoInfo/DP/Handler/GameEventHandler.cs#L112)

> Also i found code for flashduration(when downloading the zip on github) but no flashduration in the nuget version

You can use a prerelease for that.

**Comment by PMatthaei** [comment]
Thanks for the hints.

**Comment by PMatthaei** [comment]
Sorry for another question but the "eventDescriptor" player_footstep captures all hearable steps, right?

**Comment by main--** [comment]
It may or may not. We didn't test this (because it's not implemented).

Note that the CS:GO client may even ignore footstep gameevents when watching demo files as they can be recalculated from player movement data. We have seen unused/bugged gameevents before.

**Comment by PMatthaei** [comment]
Would it be safer/more accurate to calculate steps with player velocity ?

**Comment by moritzuehling** [comment]
Depends on what you are trying to do with it. And as @main-- said, we have no idea how accurate the footsteps saved in the demo are.

**Comment by PMatthaei** [comment]
I think of a realtime replay of the game(minimap style) where i want to display details about players. (mostly attacking and supporting encounters)

**Comment by shock2provide** [comment]
Why don't you just use the position (x,y,z) of every player each tick?

**Comment by PMatthaei** [comment]
I will use that. But i also ned information about their status(at best: hearable for someone, jumping, ducking, and visibility to others)

**Comment by shock2provide** [comment]
This information isn't saved in the demo file as this is simulated when playing back the demo.
So in your case you would have to figure out in which radius player can hear the footsteps and calculate the distance between two players and go from there.

About visibility / line of sight, you would have to simulate this on your own too. And this is gonna be hard as would have to use the minimap or something along these lines to find out where walls are, etc...

Jumping & ducking should be in the demo tough.

**Comment by PMatthaei** [comment]
PUSH: another event that seems to be missing is "isducking". ok not missing but all the demos i searched in ( 6 so far) only have ducking = false. Or is it just a rare case that isducking is captured?
