### ISSUE TITLE
Not all participants being listed

### ISSUE THREAD

**Issue by myluki2000** [StatsHelix/demoinfo#109]
I use this library to get all participants of a particular match from the users demo folder, but for some of the demos it will only show me some of the participants, sometimes 6, 7, 9 or all 10 of  them. This is true for both matxhmaking demos and demos from MLG Columbus

The code I'm using is the following:

(It's VB.NET but that shouldn't really make a difference)

`For Each _player As Player In demoParser.PlayingParticipants

                Dim lvItem As New ListViewItem
                    lvItem.Text = _player.Name
                    lvItem.SubItems.Add(New ListViewItem.ListViewSubItem(lvItem, _player.AdditionaInformations.Kills))
                    lvItem.SubItems.Add(New ListViewItem.ListViewSubItem(lvItem, _player.AdditionaInformations.Assists))
                    lvItem.SubItems.Add(New ListViewItem.ListViewSubItem(lvItem, _player.AdditionaInformations.Deaths))

                lvDemoPlayers.Items.Add(lvItem)
            Next`

Maybe I'm just missing something, but I can't get it to work properly

**Comment by moritzuehling** [comment]
PlayingParticipants give you the participants at a single point in time. 

Players often disconnect at the beginning or are not yet connected at the start.

**Comment by moritzuehling** [comment]
At which point in time do you display this list? Which demos at which tick exactly show this issue?

I'll close this issue until more details are provided.

**Comment by myluki2000** [comment]
I'm using .parseToEnd() so I guess that's the reason that some players are missing, because you mentioned that they might disocnnect when the game is done, but the demo is still recording, so they are not included in the list.

Is this assumption correct?

**Comment by moritzuehling** [comment]
Probably

**Comment by myluki2000** [comment]
But isn't it the purpose of .parseToEnd() to parse the whole match and not just the last tick of it?

**Comment by moritzuehling** [comment]
Yes, it parses the whole demo. However the parser doesn't aggregate.

What should PlayingParticipants.First().Position return before a player connects or after he disconnects? What name shoul it return when the name changed?

The API can only return the data at a single defined point in time.

**Comment by myluki2000** [comment]
Ok, thank you for your help :)
