### ISSUE TITLE
Demoinfo detects L4D2 Branch as csgo demos

### ISSUE THREAD

**Issue by Traderain** [StatsHelix/demoinfo#110]
Make a method or a check to detect if it is actually a csgo demo because it tries to parse:

- Alien Swarm
- Portal 2
- L4D2
demo but failes.

**Comment by Calak** [comment]
[Here](https://github.com/StatsHelix/demoinfo/pull/111) a pull request to catch this, but it must be checked cause i edited it from my smartphone.

Or you can manualy make the test I added.
