### ISSUE TITLE
Off-Topic Help: Counter Strike Global Offensive Coordinate System

### ISSUE THREAD

**Issue by PMatthaei** [StatsHelix/demoinfo#112]
I hope nobody gets offended if i post a little off topic question here but does anybody know how the coordinate system in CSGO works. Looks like they have a weird center. I want to calculate the parser koordinates to my own :)

UPDATE: found a way, and as noone seems to be interested i dont bother explaining -> CLOSED.

**Comment by 0BuRner** [comment]
I'm interested, can you explain it in this thread ? :o

**Comment by PMatthaei** [comment]
alright... the way i am handling this at the moment is:
1.
CSGO gamefiles include a folder "overview" where <mapname>.txt files are included which hold information about the "upperleft" coordinate of the corresponding map. these coordinates (posx and posy) mark the left upper corner of your map.

2. 
Given that "p" ist the position you got from the parser (f.e. p.x = 0,p.y = 0) you can get the "normal" coordinates by calculating the following.
var x = Math.Abs(posx  - p.x) 
var y = Math.Abs(posy - p.y)
This gives your coordinates which the origin in the upper left corner. but they still have high range because (~ -3000 to +3500 )

PS: This works fine for me. maybe i missed some bugs. I recommend using cl_showpos 1 ingame and look where on the minimap which coordinate is ;) Still missing are width and height. For these i had to walk the map and guess values until my custom minimap looked fine.
