### ISSUE TITLE
Confused w/ ManagedBitStream method

### ISSUE THREAD

**Issue by purplS1** [StatsHelix/demoinfo#113]
Hello,
I have been trying to get this library into Java in order to utilize it's functionality in my own project. However, I have been having some trouble with the ManagedBitStream method PeekInt. I am just a bit (lul) confused on what it is doing in the return statement line:
`return (uint)((BitConverter.ToUInt64(Buffer, (Offset / 8) & ~3) << ((8 * 8) - (Offset % (8 * 4)) - numBits)) >> ((8 * 8) - numBits));` 

I am relatively new to C# and nothing is really making sense, it just won't translate into Java for me.

**Comment by main--** [comment]
It simply reads a certain amount of bits from the buffer by first reading a `long` and then extracting the bits from that. The only nonobvious parts about this are:

* The long is guaranteed to contain the desired bits as the read has to be <= 32 bits
* We shift left to drop all bits above the ones we want and then right to drop the ones below

Sorry, but we can't teach you C#. The docs for the arithmetic operators and the `ToUInt64` clearly explain what's happening here.

**Comment by purplS1** [comment]
Alright, thanks. That should be sufficient.
