### ISSUE TITLE
BombPlanted gets fired multiple times in a single round (with only 1 bombplant).

### ISSUE THREAD

**Issue by master117** [StatsHelix/demoinfo#123]
While working the demos provided further below I noticed that demoParser.BombPlanted event gets called twice in a row on some rounds. I could avoid the resulting bugs with some roundend counter/plant counter check. Twice in a row in this case means without a RoundStart event in between, which I used to check.

Demos:
https://1drv.ms/u/s!Ans7g8s_3m0Jg4lBXpbSo7M5l3D8rA

Happens for example in round 2 of the first replay.

**Comment by master117** [comment]
BombDefused gets fired multiple times as well.

**Comment by moritzuehling** [comment]
Can you open the demos and do `demo_listimportantticks` in the CS:GO client and look if they are fired multiple times in these demos as well?

**Comment by master117** [comment]
Multiple restarts of the game seem to have triggered a bug in my Code, the event apparently got subscribed to twice. I'm sorry, my bad.
