### ISSUE TITLE
No `RoundAnnounceMatchStarted` event in one of my demos, and empty `AdditionaInformations` for players

### ISSUE THREAD

**Issue by mecwerks** [StatsHelix/demoinfo#137]
Hello, I've been using this library to parse GOTV demos from 10mans me and my friends play on our own server. For the most part everything has worked fine with the exception of 1 match. All other demos always get the `RoundAnnounceMatchStarted` event and I use this to reset tracking information and mark when i need to start watching for other events. I tried getting around it missing by subscribing to just the `MatchStarted` event, but noticed after the demo is parsed, all players `AdditionaInformations` is 0 except for Ping. Any ideas why this would be the case and how I could avoid this being an issue in our other demos?

[Demo File](https://www.dropbox.com/sh/wzp1mc747dwfcbm/AADH2Z1zpp7AoOdEJHYjLMtCa?dl=0&preview=pug_de_train_2017-12-18_21.dem)

Thanks for any help.

**Comment by mecwerks** [comment]
So although I'm not gettting the RoundAnnounceMatchStarted event, I can circumvent this by subscribing to `MatchStarted`, and the reason the stats were empty at the end of parsing is due to another MatchStarted event being triggered and re-clearing everything. I tried re-working my code to only account for a single start-to-finish match, but can't seem to find a good event to subscribe to on match end except for `WinPanelMatch` which doesn't seem to get called.

**Comment by mecwerks** [comment]
Realized that this match never had an actual end event as we force ended it early, need to work around this in my own code :)

**Comment by moritzuehling** [comment]
Welcome to working with demos :)
