### ISSUE TITLE
Somewhere players are lost

### ISSUE THREAD

**Issue by ZUBAT** [StatsHelix/demoinfo#142]
After the work of the parser, the information about the demo stores 7 players, In fact, there are 10 people in the game. How can this be? What am I doing wrong ?
My code for parse. After that I do the serialization of the parser object in the JSON format
![image](https://user-images.githubusercontent.com/10541834/41445897-1ca26a66-707f-11e8-995d-04d25bf8eb1e.png)

**Comment by ZUBAT** [comment]
Sorry/ i am readed closed issues, and find asnwer

**Comment by moritzuehling** [comment]
For future reference: After the game ends, but before ther ecording of the demo stops, 3+ players disconnect.
