### ISSUE TITLE
Crash on parser.ParseToEnd();

### ISSUE THREAD

**Issue by gdhsnlvr** [StatsHelix/demoinfo#149]
Crash at line
`parser.ParseToEnd();`
on this demos
https://www.hltv.org/matches/2320069/tyloo-vs-gambit-iem-katowice-2018 map 3 (de_cache).
https://www.hltv.org/matches/2320066/sk-vs-astralis-iem-katowice-2018 map 2 (de_overpass).
exception: EndOfStreamException
(version is last stable realise 1.2.0)

**Comment by main--** [comment]
Truncated demo files are not uncommon and it is the user's (your) responsibility to deal with them.

You could for example catch the `EndOfStreamException` or just stop parsing at the end of the game.
