### ISSUE TITLE
PacketEntitesHandler.cs string 132

### ISSUE THREAD

**Issue by ZUBAT** [StatsHelix/demoinfo#153]
Good day. Faced a problem when parsing demo. 

Unhandled exception: System.NotImplementedException: Method or operation is not implemented.
   в DemoInfo.DP.Handler.PacketEntitesHandler.PropertyCollector..ctor(Entity underlying, IList`1 capture) в C:\MMBot\CSGODemoViewer\demoinfo\DemoInfo\DP\Handler\PacketEntitesHandler.cs:строка 132
   в DemoInfo.DP.Handler.PacketEntitesHandler.ReadEnterPVS(IBitStream reader, Int32 id, DemoParser parser) в C:\MMBot\CSGODemoViewer\demoinfo\DemoInfo\DP\Handler\PacketEntitesHandler.cs:строка 93
   в DemoInfo.DP.Handler.PacketEntitesHandler.Apply(PacketEntities packetEntities, IBitStream reader, DemoParser parser) в C:\MMBot\CSGODemoViewer\demoinfo\DemoInfo\DP\Handler\PacketEntitesHandler.cs:строка 35
   в DemoInfo.PacketEntities.Parse(IBitStream bitstream, DemoParser parser) в C:\MMBot\CSGODemoViewer\demoinfo\DemoInfo\DP\FastNetmessages\PacketEntities.cs:строка 31
   в DemoInfo.DP.DemoPacketParser.ParsePacket(IBitStream bitstream, DemoParser demo) в C:\MMBot\CSGODemoViewer\demoinfo\DemoInfo\DP\DemoPacketParser.cs:строка 38
   в DemoInfo.DemoParser.ParseDemoPacket() в C:\MMBot\CSGODemoViewer\demoinfo\DemoInfo\DemoParser.cs:строка 746
   в DemoInfo.DemoParser.ParseTick() в C:\MMBot\CSGODemoViewer\demoinfo\DemoInfo\DemoParser.cs:строка 726
   в DemoInfo.DemoParser.ParseNextTick() в C:\MMBot\CSGODemoViewer\demoinfo\DemoInfo\DemoParser.cs:строка 595
   в DemoInfo.DemoParser.ParseToEnd(CancellationToken token) в C:\MMBot\CSGODemoViewer\demoinfo\DemoInfo\DemoParser.cs:строка 580
   в CSGODemoViewer.Analyzer.AnalyzeDemo() в C:\MMBot\CSGODemoViewer\CSGODemoViewer\Analyzer.cs:строка 149
   в CSGODemoViewer.Program.Main(String[] args) в C:\MMBot\CSGODemoViewer\CSGODemoViewer\Program.cs:строка 20

**Comment by moritzuehling** [comment]
Hey,

was this a new demo from after the "Danger Zone"-update?

**Comment by ZUBAT** [comment]
I can't say with 100 % certainty, but it's kind of from the old game mode

http://replay182.valve.net/730/003316106651097890976_1015458357.dem.bz2

**Comment by ZUBAT** [comment]
Yes it is normal dust2 competitive mode

**Comment by moritzuehling** [comment]
The relevant part is if it's from the new update - if that's the case, they
might have changed networking.

Gamemode is less discriminating than which update it was.

>
