### ISSUE TITLE
Player position reported switches to different player after death

### ISSUE THREAD

**Issue by lasse16** [StatsHelix/demoinfo#156]
This is more of a heads-up instead of a bug. A Bethesda feature, sortof ...

I wrote a snippet of code to get a player's path in each round, by subscribing to the tickDone event and adding each player's current position to a list. Now I noticed some rather unusual paths; in short, once the player is dead, the position reported for this player is the position of a different second player ( might be the killer's pos - didnt check). 

This can be simply bypassed by checking if the player is alive each tick and if not adding the last position alive to the list every tick.  
Still think of it as a noteworthy feature.

**Comment by moritzuehling** [comment]
It switches to the player they are spectating, to be exact.
