### ISSUE TITLE
bullet_impact event

### ISSUE THREAD

**Issue by tobuhl** [StatsHelix/demoinfo#161]
Hi,

I wanted to use your library because I am interested in bullet_impact events in demos, but it seems that it is not being parsed since there isn't even a case for it in the game event handler: https://github.com/StatsHelix/demoinfo/blob/master/DemoInfo/DP/Handler/GameEventHandler.cs

Is it somehow possible to get this event?

**Comment by master117** [comment]
I'm not sure if that event exists, sounds like something calculated client side. If it does, you can add an event handler like the others that exist. Weapon fired should probably be quite similar to it, check where it originates from and add your own handler next to it.

**Comment by tobuhl** [comment]
Alright, I see. It makes sense that non-hit bullet impacts aren't networked. I just thought that all (https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events) events are networked. 

Thank you for your quick reply.
