### ISSUE TITLE
System.Exception: 'Roy said I should throw this.'

### ISSUE THREAD

**Issue by KilinW** [StatsHelix/demoinfo#168]
Hello, I'm kind of a beginner to c#.
And I'm now trying to familiar with this package. Cause i want to know all the physic info of a player in a demo.
But I saw a weird exception in DemoInfo.ST.StringTableParser.ParseStringTable().
That make my extremely simple demo parse code not working.
Is this normal?

```
using System.IO;
using DemoInfo;

namespace csproj
{
    class Program
    {
        static void Main(string[] args)
        {
            DemoParser dem = new DemoParser(File.OpenRead("cyberwave.dem"));
            dem.ParseHeader();
            dem.ParseToEnd();
        }
    }
}
```

**Comment by master117** [comment]
Please see if you have these issues with a mm demo.

**Comment by KilinW** [comment]
Hello master117. 
I use one of my GOTV demo.
steam://rungame/730/76561202255233023/+csgo_download_match%20CSGO-BsMJ8-UG8Lj-oRzSn-x6z5X-Nk2pH
And it still has the same issue
They all got the exception after 10~30tick.

###I change my visual studio to English for screenshot and the exception become

System.NotImplementedException: 'The method or operation is not implemented.'

![image](https://user-images.githubusercontent.com/49479323/113480605-b02bdf00-94c7-11eb-9de2-146103b545f6.png)

but they got exception at the same tick.
I saw someone post the same issue before.

**Comment by master117** [comment]
Try this: https://github.com/StatsHelix/demoinfo/issues/165

You have to build the library yourself since there has been no new release for years.

**Comment by KilinW** [comment]
I have to apologize. I only write simple language like python.
And it don't need to build. We just write code and run it.
It looks like that i need to disabling signed assembly when building.
But i got these errors when I try to build DemoInfo.

Cycle detected.   DemoInfo -> DemoInfo (>= 1.2.0).	

The BaseOutputPath/OutputPath property is not set for project

Don't really know how to build.
Can you give me some hint?
![image](https://user-images.githubusercontent.com/49479323/113482414-3dbffc80-94d1-11eb-927c-8b8703e58bf8.png)

**Comment by KilinW** [comment]
I'm really sorry again for asking such dumb question.
But I really can't figure it out...

**Comment by master117** [comment]
Cycle means that you have a library twice or that a library is referencing itself. You do not need the NuGet package if you also add the library.

From the beginning.

1, Make a solution
2. Add your project
3. Import DemoInfo project
4. Change settings in DemoInfo project to disable signed assembly
5. Import DemoInfo project in your project via browse dialog. DO not add DemoInfo via NuGet

**Comment by KilinW** [comment]
Hello. I appreciate your help and it totally works.
I can now parse the whole GOTV demo now.
But I still can't parse a POV demo.
The POV demo is a random community map.
Normally start with record command and stop with stop command.
It's pretty weird that before I rebuild, I can parse about 10~30 ticks.
But now I can't even parse 1 tick. I can only parse header of demo.
![image](https://user-images.githubusercontent.com/49479323/113488444-c39f7000-94f0-11eb-9fd5-be48c9abed7e.png)

**Comment by master117** [comment]
POV demo parsing is not supported by this library, as they are wildly inconsistent. 

You could try https://github.com/akiver/CSGO-Demos-Manager/tree/master/demoinfo (A newer fork of demoinfo that is still being semi maintained)
Or https://github.com/saul/demofile

But I don't think any public/open source library supports POV demo parsing. Some POV will still parse, but there is no guarantee.

**Comment by KilinW** [comment]
ok got that.
Thank you very much!!
