### ISSUE TITLE
get rank (CSGO)

### ISSUE THREAD

**Issue by clankill3r** [StatsHelix/demoinfo#95]
Would it by any means be possible to get the rank of a player?

**Comment by moritzuehling** [comment]
See: https://github.com/EHVAG/demoinfo/issues/45#issuecomment-114562405

If you implement UserMessage of the RankUp-Servermessage cleanly, I'm open for a PR!

**Comment by tpf89** [comment]
It's not implement yet, is it? Don't want to make any pressure, just wondering, 'cause it's implemented in the CSGO Demos Manager. :)

**Comment by main--** [comment]
@tpf89 This was implemented in #97 (CSGO Demos Manager uses DemoInfo).
