### ISSUE TITLE
How do we use the ServerRankUpdate?

### ISSUE THREAD

**Issue by TomSmith27** [StatsHelix/demoinfo#96]
I dont have those events to attach to, these guys seem to have it working but the DLL isnt signed.

http://csgo-demos-manager.com/

**Comment by moritzuehling** [comment]
https://github.com/EHVAG/demoinfo#prereleases

**Comment by TomSmith27** [comment]
I Installed the pre-release version using Nuget but I still don't have access to the ServerRankUpdateEventArgs Event am i just doing this wrong? Or do i need to do something with the slow_protobuf?

Thanks

**Comment by moritzuehling** [comment]
You need to enable `SLOW_PROTOBUF` in the compile-options, yes. However, you could also implement the message properly as described by main here:

https://github.com/EHVAG/demoinfo/issues/91#issuecomment-194492968

**Comment by moritzuehling** [comment]
Closed because the PR was merged
